### ISSUE TITLE
Add test for scaling up a function

### ISSUE THREAD

**Issue by ivanayov** [openfaas/certifier#13]
Use `/system/scale-function` for scaling .

Test cases:
1x without limits
1x with limits
1x autoscaling disabled
1x 0 to 1 replicas

**Comment by ivanayov** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Let's do the first PR where we scale using the manual endpoint then check the API for how many replicas we expected. Once that's merged, we can look at the next scenario to cover.

**Comment by ivanayov** [comment]
@alexellis I'm now on the TODO list from #14

**Comment by ivanayov** [comment]
Scaling limit restrictions are ignored when calling `/system/scale-function`.
Tested manually separately from the test. I'm going to remove the labels from the code for now and we can consider this as an separate issue.
