### ISSUE TITLE
Add secret CRUD to the test-suite

### ISSUE THREAD

**Issue by alexellis** [openfaas/certifier#16]
We should add a scenario to test the new secret CRUD behaviour added in gateway 0.9.14 and the corresponding faas-swarm / faas-netes / openfaas-operator versions.

Suggested test scenario:

* Create
* Invoke (function that prints the secret)
* List
* Update
* Invoke (function that prints the secret)
* Delete

**Comment by roncrivera** [comment]
Hi @alex, I would like to work on this. Thanks!

**Comment by roncrivera** [comment]
hi @alexellis, i still haven't started work on this. if someone from the community would like to pick this up, please feel free to take this one.

i am still picking up golang and not satisfied with my progress :-( so don't want that to be an impediment/blocker in completing this.

**Comment by alexellis** [comment]
Hi Ed, you've had this one for about a month are you still planning on working on it?

**Comment by matipan** [comment]
I'll be happy to take on this one :+1:

**Comment by alexellis** [comment]
That would be awesome thanks @matipan 👍

**Comment by codegold79** [comment]
I'm going to give this one a go. Hopefully, I'm not the fourth person to not be able to get this test suite completed.

Derek assign: me

**Comment by codegold79** [comment]
@alexellis, I think I'll need a manual assignment.

**Comment by alexellis** [comment]
Just go for it :+1:

**Comment by codegold79** [comment]
I installed Docker Swarm, disabled basic auth, and ran the test suite. Unfortunately, all tests except for the update and delete parts fail. When I use PostMan, I at times can update/delete, and other times, I can't. I don't get it. I'm not sure what to do to figure this out.

**Comment by codegold79** [comment]
@alexellis, not sure why this didn't get closed when PR #22 was merged.
