### ISSUE TITLE
Add tests for redirection

### ISSUE THREAD

**Issue by mario-mazo** [openfaas/certifier#18]
There are no tests for http redirection use cases using the golang-middleware template

**Comment by alexellis** [comment]
@ewilde PTAL?

**Comment by alexellis** [comment]
The gateway needs tests to prove that redirection is not broken in any subsequent versions.

Alex

**Comment by ewilde** [comment]
@alexellis / @mario-mazo happy to take a look, please can you edit this issue and explain the problem in some more detail.

i.e.
```
<!--- Provide a general summary of the issue in the Title above -->

## Expected Behaviour
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->

## Current Behaviour
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->

```

**Comment by pcsx22** [comment]
@alexellis  do you mean test cases for scenarios like redirection of "/" to "/ui" by gateway?

**Comment by alexellis** [comment]
No. HTTP request codes. Support was added several months ago, but there are no tests for this in thy certifier.

**Comment by alexellis** [comment]
@LucasRoesler 

The components can follow a redirect emitted from a function, that must not happen, it needs to be propagated up to the caller of the gateway.

**Comment by LucasRoesler** [comment]
That is a perfect description, i can add that pretty easily

**Comment by LucasRoesler** [comment]
@alexellis this will require a new custom function, how do we want to handle publishing that function?  Would it go to `functions/redirector:latest`?
