### ISSUE TITLE
Auto-scaling e2e tests

### ISSUE THREAD

**Issue by alexellis** [openfaas/certifier#20]
## Description

Auto-scaling e2e tests are required to check for compliance and to test regression.

Each test case can be submitted in a separate PR starting with the simplest (1st) test-case.

## Test case: min scale

When using the `com.openfaas.scale.min` label, there should be a minimum number of replicas available via the API.

## Test case: scale from zero

1) Deploy function
2) Scale to zero
3) Wait until no ready replicas
4) Invoke function and make sure result is returned as 200

## Test case: auto-scaling up > min, then returning down to min

Test case may take up to 30s or 1m to complete, but can be run easily.

1) Deploy a function with min = 1, max = 2
2) Invoke function in a loop
3) Wait until replicas > min
4) Stop invoking function
5) Wait until function replicas returns to min

**Comment by kwojcicki** [comment]
Derek assign: me

**Comment by alexellis** [comment]
@kwojcicki if you'd like access to Derek, send a PR to .DEREK.yml in openfaas/faas - he'll then acknowledge you, but GitHub won't allow assignments to users who are not in the GitHub org.

**Comment by LucasRoesler** [comment]
Derek assign: me
