### ISSUE TITLE
Consolidate the Test_Access_Secret and the Secret CRUD test

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/certifier#31]
Testing a function that can access a secret is now covered by first step of `Test_SecretCRUD`.  We should remove `Test_Access_Secret` and all of the related setup/cleanup code to help simplify  the certifier code base

At the same time, it might be good to break the `Test_SecretCRUD` into subtests using `t.Run` to make it clearer in the test logs and in the codebase itself that this `Test_Access_Secret` case is covered.

**Comment by alexellis** [comment]
Go for it 👍
