### ISSUE TITLE
Test the namespaces listing endpoint

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/certifier#63]
Each provider that supports multiple namespaces needs to support list available namespaces, the endpoint is `/system/namespaces`. This should be the first test case we add for multinamespace support as part of #61 

https://github.com/openfaas/faas-provider/blob/bc0f26cae70c1b3ba2a595cea8bfb8c04925d5c6/serve.go#L68

For faas-netes the implementation is here https://github.com/openfaas/faas-netes/blob/e5cf64dcf4d01f04636d2ffe736be110981b83c5/pkg/handlers/namespaces.go#L22-L48 It requires deployment with a ClusterRole and annotations added to the permitted namespaces.

We need to be able to confirm both of these cases: 

1. when deployed with multi-namespace support disabled, the endpoint should only return a single namespace, the default namesapce (usually `openfaas-fn`)
2. when deployed with multi-namespace support enabled, it should return it should return each of the configured namespaces _and_ it should also include the default namespace. 

I don't think it requires writing multiple test cases, rather the ideal situation is that the one test can work to run against deployments/configurations.

**Comment by nitishkumar71** [comment]
I will work on this to as next step to support #61
